apiVersion: apps/v1
kind: Deployment
metadata:
  name: azmi1-nginx-deployment
spec:
  selector:
    matchLabels:
      app: azmi1-nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: azmi1-nginx
    spec:
      containers:
        - name: azmi1-nginx-deployment
          image: nginx:latest
          ports:
            - containerPort: 80
